### PR TITLE
fix(otelsql): record error and status when SQL returns an error

### PR DESCRIPTION
**Pull request by empire**
The Span ends early when SQL returns an error, which prevents Otelsql from recording the error.
This commit fixes this issue by deferring the Span.End() call.

Fixes: #115

### CODE REVIEW

**Comment by empire** [comment]
@vmihailenco , could you please take a look at this P.R.

Thanks

**Comment by vmihailenco** [comment]
@empire thanks for the fix.

**Comment by empire** [comment]
@vmihailenco Thanks for merging this pull request. When do you plan to release this fix?

**Comment by vmihailenco** [comment]
@empire v0.2.4 should be available withing few minutes.

**Comment by empire** [comment]
It sounds great. Thank you.

**Pull request merged**
