### PR TITLE
fix: ctx fields not propegating to logger

### PR DESCRIPTION
**Pull request by mrsufgi**
Hey :) Cool pkg. 
I've been trying it out with a Fiber + otel + zap setup, works good. execpt from mild inconsistencies in behavoiur (which I fixed in my PR) 

Code:
```
log := otelzap.New(zap.L(), otelzap.WithTraceIDField(true), otelzap.WithMinLevel(zap.DebugLevel))
log.Ctx(c.UserContext()).Info("no trace_id field!")
log.InfoContext(c.UserContext(), "have trace_id field :)")
```

Results in
```
2021-11-25T08:50:53.737Z        INFO    otelzap@v0.1.5/otelzap.go:259   no trace_id field! 
2021-11-25T08:50:53.737Z        INFO    otelzap@v0.1.5/otelzap.go:101   have trace_id field :)     {"trace_id": "40ed735823dc565b8b9bf7db2da42b10"}
```

Btw the tracing in my otel-collector works just fine, it's just the logger :)

### CODE REVIEW

**Comment by vmihailenco** [comment]
Thanks :+1: 

Out of curiosity, how your setup looks like? Do you use https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/filelogreceiver with some backend or ...? Any additional processing / parsing in OTel collector?

**Comment by mrsufgi** [comment]
Actually, my setup is pretty simple since I'm new with otel.

My setup has Loki and Tempo as backend. Otel collector as a sidecar that receive otlp and export otlp to Tempo.
  
In Loki I have derrived fields setup for trace_id.

I plan on generating and propagating trace_id from my north-south (traefik).

I still have alot of unknows on how traces and logs play together. 
 Would be happy to keep discussing it with you :)

**Comment by vmihailenco** [comment]
OpenTelemetry logs are in alpha state so that's why I am curious how you are using them. In theory, we will have OpenTelemetry logging API which supports `trace_id` out-of-the-box so you won't need to include trace_id in log message. But for now logging API is only available for Python so you are probably doing everything right with the stack you have.

In Uptrace, logs are part of the trace (just like errors/exceptions) so I don't need `otelzap.WithTraceIDField(true)` and/or logging API.

**Comment by mrsufgi** [comment]
@vmihailenco It's also worth mentioning that propagating `trace_id` to logs is only available with `L()` and not with SugaredLogger.

**Pull request merged**
